// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.morodog.domain;

import ar.edu.um.programacion2.morodog.domain.LinkDataOnDemand;
import ar.edu.um.programacion2.morodog.domain.LinkIntegrationTest;
import ar.edu.um.programacion2.morodog.service.LinkService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LinkIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LinkIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LinkIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LinkIntegrationTest: @Transactional;
    
    @Autowired
    LinkDataOnDemand LinkIntegrationTest.dod;
    
    @Autowired
    LinkService LinkIntegrationTest.linkService;
    
    @Test
    public void LinkIntegrationTest.testCountAllLinks() {
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", dod.getRandomLink());
        long count = linkService.countAllLinks();
        Assert.assertTrue("Counter for 'Link' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LinkIntegrationTest.testFindLink() {
        Link obj = dod.getRandomLink();
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Link' failed to provide an identifier", id);
        obj = linkService.findLink(id);
        Assert.assertNotNull("Find method for 'Link' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Link' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LinkIntegrationTest.testFindAllLinks() {
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", dod.getRandomLink());
        long count = linkService.countAllLinks();
        Assert.assertTrue("Too expensive to perform a find all test for 'Link', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Link> result = linkService.findAllLinks();
        Assert.assertNotNull("Find all method for 'Link' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Link' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LinkIntegrationTest.testFindLinkEntries() {
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", dod.getRandomLink());
        long count = linkService.countAllLinks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Link> result = linkService.findLinkEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Link' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Link' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LinkIntegrationTest.testFlush() {
        Link obj = dod.getRandomLink();
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Link' failed to provide an identifier", id);
        obj = linkService.findLink(id);
        Assert.assertNotNull("Find method for 'Link' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLink(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Link' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LinkIntegrationTest.testUpdateLinkUpdate() {
        Link obj = dod.getRandomLink();
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Link' failed to provide an identifier", id);
        obj = linkService.findLink(id);
        boolean modified =  dod.modifyLink(obj);
        Integer currentVersion = obj.getVersion();
        Link merged = linkService.updateLink(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Link' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LinkIntegrationTest.testSaveLink() {
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", dod.getRandomLink());
        Link obj = dod.getNewTransientLink(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Link' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Link' identifier to be null", obj.getId());
        try {
            linkService.saveLink(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Link' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LinkIntegrationTest.testDeleteLink() {
        Link obj = dod.getRandomLink();
        Assert.assertNotNull("Data on demand for 'Link' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Link' failed to provide an identifier", id);
        obj = linkService.findLink(id);
        linkService.deleteLink(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Link' with identifier '" + id + "'", linkService.findLink(id));
    }
    
}
