// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.morodog.domain;

import ar.edu.um.programacion2.morodog.domain.Link;
import ar.edu.um.programacion2.morodog.domain.LinkDataOnDemand;
import ar.edu.um.programacion2.morodog.service.LinkService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LinkDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LinkDataOnDemand: @Component;
    
    private Random LinkDataOnDemand.rnd = new SecureRandom();
    
    private List<Link> LinkDataOnDemand.data;
    
    @Autowired
    LinkService LinkDataOnDemand.linkService;
    
    public Link LinkDataOnDemand.getNewTransientLink(int index) {
        Link obj = new Link();
        setNombre(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void LinkDataOnDemand.setNombre(Link obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 50) {
            nombre = new Random().nextInt(10) + nombre.substring(1, 50);
        }
        obj.setNombre(nombre);
    }
    
    public void LinkDataOnDemand.setUrl(Link obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public Link LinkDataOnDemand.getSpecificLink(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Link obj = data.get(index);
        Long id = obj.getId();
        return linkService.findLink(id);
    }
    
    public Link LinkDataOnDemand.getRandomLink() {
        init();
        Link obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return linkService.findLink(id);
    }
    
    public boolean LinkDataOnDemand.modifyLink(Link obj) {
        return false;
    }
    
    public void LinkDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = linkService.findLinkEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Link' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Link>();
        for (int i = 0; i < 10; i++) {
            Link obj = getNewTransientLink(i);
            try {
                linkService.saveLink(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
