// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.morodog.domain;

import ar.edu.um.programacion2.morodog.domain.RePublicacionDataOnDemand;
import ar.edu.um.programacion2.morodog.domain.RePublicacionIntegrationTest;
import ar.edu.um.programacion2.morodog.service.RePublicacionService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RePublicacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RePublicacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RePublicacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RePublicacionIntegrationTest: @Transactional;
    
    @Autowired
    RePublicacionDataOnDemand RePublicacionIntegrationTest.dod;
    
    @Autowired
    RePublicacionService RePublicacionIntegrationTest.rePublicacionService;
    
    @Test
    public void RePublicacionIntegrationTest.testCountAllRePublicacions() {
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", dod.getRandomRePublicacion());
        long count = rePublicacionService.countAllRePublicacions();
        Assert.assertTrue("Counter for 'RePublicacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RePublicacionIntegrationTest.testFindRePublicacion() {
        RePublicacion obj = dod.getRandomRePublicacion();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to provide an identifier", id);
        obj = rePublicacionService.findRePublicacion(id);
        Assert.assertNotNull("Find method for 'RePublicacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RePublicacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RePublicacionIntegrationTest.testFindAllRePublicacions() {
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", dod.getRandomRePublicacion());
        long count = rePublicacionService.countAllRePublicacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'RePublicacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RePublicacion> result = rePublicacionService.findAllRePublicacions();
        Assert.assertNotNull("Find all method for 'RePublicacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RePublicacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RePublicacionIntegrationTest.testFindRePublicacionEntries() {
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", dod.getRandomRePublicacion());
        long count = rePublicacionService.countAllRePublicacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RePublicacion> result = rePublicacionService.findRePublicacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RePublicacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RePublicacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RePublicacionIntegrationTest.testFlush() {
        RePublicacion obj = dod.getRandomRePublicacion();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to provide an identifier", id);
        obj = rePublicacionService.findRePublicacion(id);
        Assert.assertNotNull("Find method for 'RePublicacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRePublicacion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RePublicacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RePublicacionIntegrationTest.testUpdateRePublicacionUpdate() {
        RePublicacion obj = dod.getRandomRePublicacion();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to provide an identifier", id);
        obj = rePublicacionService.findRePublicacion(id);
        boolean modified =  dod.modifyRePublicacion(obj);
        Integer currentVersion = obj.getVersion();
        RePublicacion merged = rePublicacionService.updateRePublicacion(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RePublicacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RePublicacionIntegrationTest.testSaveRePublicacion() {
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", dod.getRandomRePublicacion());
        RePublicacion obj = dod.getNewTransientRePublicacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RePublicacion' identifier to be null", obj.getId());
        try {
            rePublicacionService.saveRePublicacion(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'RePublicacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RePublicacionIntegrationTest.testDeleteRePublicacion() {
        RePublicacion obj = dod.getRandomRePublicacion();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RePublicacion' failed to provide an identifier", id);
        obj = rePublicacionService.findRePublicacion(id);
        rePublicacionService.deleteRePublicacion(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'RePublicacion' with identifier '" + id + "'", rePublicacionService.findRePublicacion(id));
    }
    
}
