// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.morodog.domain;

import ar.edu.um.programacion2.morodog.domain.Tendencia;
import ar.edu.um.programacion2.morodog.domain.TendenciaDataOnDemand;
import ar.edu.um.programacion2.morodog.service.TendenciaService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TendenciaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TendenciaDataOnDemand: @Component;
    
    private Random TendenciaDataOnDemand.rnd = new SecureRandom();
    
    private List<Tendencia> TendenciaDataOnDemand.data;
    
    @Autowired
    TendenciaService TendenciaDataOnDemand.tendenciaService;
    
    public Tendencia TendenciaDataOnDemand.getNewTransientTendencia(int index) {
        Tendencia obj = new Tendencia();
        setNombre(obj, index);
        return obj;
    }
    
    public void TendenciaDataOnDemand.setNombre(Tendencia obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 50) {
            nombre = nombre.substring(0, 50);
        }
        obj.setNombre(nombre);
    }
    
    public Tendencia TendenciaDataOnDemand.getSpecificTendencia(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Tendencia obj = data.get(index);
        Long id = obj.getId();
        return tendenciaService.findTendencia(id);
    }
    
    public Tendencia TendenciaDataOnDemand.getRandomTendencia() {
        init();
        Tendencia obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return tendenciaService.findTendencia(id);
    }
    
    public boolean TendenciaDataOnDemand.modifyTendencia(Tendencia obj) {
        return false;
    }
    
    public void TendenciaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = tendenciaService.findTendenciaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Tendencia' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Tendencia>();
        for (int i = 0; i < 10; i++) {
            Tendencia obj = getNewTransientTendencia(i);
            try {
                tendenciaService.saveTendencia(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
