// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.morodog.domain;

import ar.edu.um.programacion2.morodog.domain.TendenciaDataOnDemand;
import ar.edu.um.programacion2.morodog.domain.TendenciaIntegrationTest;
import ar.edu.um.programacion2.morodog.service.TendenciaService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TendenciaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TendenciaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TendenciaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TendenciaIntegrationTest: @Transactional;
    
    @Autowired
    TendenciaDataOnDemand TendenciaIntegrationTest.dod;
    
    @Autowired
    TendenciaService TendenciaIntegrationTest.tendenciaService;
    
    @Test
    public void TendenciaIntegrationTest.testCountAllTendencias() {
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", dod.getRandomTendencia());
        long count = tendenciaService.countAllTendencias();
        Assert.assertTrue("Counter for 'Tendencia' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TendenciaIntegrationTest.testFindTendencia() {
        Tendencia obj = dod.getRandomTendencia();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to provide an identifier", id);
        obj = tendenciaService.findTendencia(id);
        Assert.assertNotNull("Find method for 'Tendencia' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tendencia' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TendenciaIntegrationTest.testFindAllTendencias() {
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", dod.getRandomTendencia());
        long count = tendenciaService.countAllTendencias();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tendencia', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tendencia> result = tendenciaService.findAllTendencias();
        Assert.assertNotNull("Find all method for 'Tendencia' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tendencia' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TendenciaIntegrationTest.testFindTendenciaEntries() {
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", dod.getRandomTendencia());
        long count = tendenciaService.countAllTendencias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tendencia> result = tendenciaService.findTendenciaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tendencia' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tendencia' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TendenciaIntegrationTest.testFlush() {
        Tendencia obj = dod.getRandomTendencia();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to provide an identifier", id);
        obj = tendenciaService.findTendencia(id);
        Assert.assertNotNull("Find method for 'Tendencia' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTendencia(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tendencia' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TendenciaIntegrationTest.testUpdateTendenciaUpdate() {
        Tendencia obj = dod.getRandomTendencia();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to provide an identifier", id);
        obj = tendenciaService.findTendencia(id);
        boolean modified =  dod.modifyTendencia(obj);
        Integer currentVersion = obj.getVersion();
        Tendencia merged = tendenciaService.updateTendencia(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tendencia' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TendenciaIntegrationTest.testSaveTendencia() {
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", dod.getRandomTendencia());
        Tendencia obj = dod.getNewTransientTendencia(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tendencia' identifier to be null", obj.getId());
        try {
            tendenciaService.saveTendencia(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Tendencia' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TendenciaIntegrationTest.testDeleteTendencia() {
        Tendencia obj = dod.getRandomTendencia();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tendencia' failed to provide an identifier", id);
        obj = tendenciaService.findTendencia(id);
        tendenciaService.deleteTendencia(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Tendencia' with identifier '" + id + "'", tendenciaService.findTendencia(id));
    }
    
}
