// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.morodog.domain;

import ar.edu.um.programacion2.morodog.domain.Relacion;
import ar.edu.um.programacion2.morodog.domain.Usuario;
import ar.edu.um.programacion2.morodog.domain.UsuarioDataOnDemand;
import ar.edu.um.programacion2.morodog.domain.Vinculo;
import ar.edu.um.programacion2.morodog.domain.VinculoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VinculoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VinculoDataOnDemand: @Component;
    
    private Random VinculoDataOnDemand.rnd = new SecureRandom();
    
    private List<Vinculo> VinculoDataOnDemand.data;
    
    @Autowired
    UsuarioDataOnDemand VinculoDataOnDemand.usuarioDataOnDemand;
    
    public Vinculo VinculoDataOnDemand.getNewTransientVinculo(int index) {
        Vinculo obj = new Vinculo();
        setIdUsuario(obj, index);
        setIdUsuarioRelacion(obj, index);
        setRelacion(obj, index);
        return obj;
    }
    
    public void VinculoDataOnDemand.setIdUsuario(Vinculo obj, int index) {
        Usuario IdUsuario = usuarioDataOnDemand.getRandomUsuario();
        obj.setIdUsuario(IdUsuario);
    }
    
    public void VinculoDataOnDemand.setIdUsuarioRelacion(Vinculo obj, int index) {
        Long idUsuarioRelacion = new Integer(index).longValue();
        obj.setIdUsuarioRelacion(idUsuarioRelacion);
    }
    
    public void VinculoDataOnDemand.setRelacion(Vinculo obj, int index) {
        Relacion relacion = Relacion.class.getEnumConstants()[0];
        obj.setRelacion(relacion);
    }
    
    public Vinculo VinculoDataOnDemand.getSpecificVinculo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Vinculo obj = data.get(index);
        Long id = obj.getId();
        return Vinculo.findVinculo(id);
    }
    
    public Vinculo VinculoDataOnDemand.getRandomVinculo() {
        init();
        Vinculo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Vinculo.findVinculo(id);
    }
    
    public boolean VinculoDataOnDemand.modifyVinculo(Vinculo obj) {
        return false;
    }
    
    public void VinculoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Vinculo.findVinculoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Vinculo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Vinculo>();
        for (int i = 0; i < 10; i++) {
            Vinculo obj = getNewTransientVinculo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
