// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.um.programacion2.morodog.domain;

import ar.edu.um.programacion2.morodog.domain.VinculoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VinculoDataOnDemand_Roo_Configurable {
    
    declare @type: VinculoDataOnDemand: @Configurable;
    
}
